name: GitHub Pages

on:
  push:
    branches:
      - main  # 如果你的默认分支是main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # 获取Hugo主题
          fetch-depth: 0    # 获取所有历史以便于lastmod等

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.147.9"
          extended: true

      - name: Build
        run: |
          hugo --gc --minify --cleanDestinationDir --environment development
          # 双重保险：检查 CNAME 是否存在
          if [ ! -f public/CNAME ]; then
            echo "heeler-deer.top" > public/CNAME
          fi  
      - name: Check Hugo Version
        run: hugo version

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public